-- MySQL Script generated by MySQL Workbench
-- Tue Apr  3 16:09:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema masalama_carkila
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema masalama_carkila
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `masalama_carkila` DEFAULT CHARACTER SET utf8 ;
USE `masalama_carkila` ;

-- -----------------------------------------------------
-- Table `masalama_carkila`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `masalama_carkila`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `midName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `city` VARCHAR(15) NOT NULL,
  `sex` VARCHAR(6) NOT NULL,
  `birthDate` VARCHAR(45) NOT NULL,
  `mobileNumber` VARCHAR(13) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masalama_carkila`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `masalama_carkila`.`Owner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `license_num` VARCHAR(45) NOT NULL,
  `license_expiry` DATE NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `license_num_UNIQUE` (`license_num` ASC),
  INDEX `fk_Vehicle Owner_User_idx` (`User_id` ASC),
  CONSTRAINT `fk_Vehicle Owner_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `masalama_carkila`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masalama_carkila`.`Renter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `masalama_carkila`.`Renter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `govt_id` BLOB NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Vehicle Renter_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Vehicle Renter_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `masalama_carkila`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masalama_carkila`.`Feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `masalama_carkila`.`Feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `feedback` VARCHAR(200) NULL,
  `rating` INT NULL,
  `date` DATE NULL,
  `Renter_id` INT NOT NULL,
  `Owner_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Feedback_Renter1_idx` (`Renter_id` ASC),
  INDEX `fk_Feedback_Owner1_idx` (`Owner_id` ASC),
  CONSTRAINT `fk_Feedback_Renter1`
    FOREIGN KEY (`Renter_id`)
    REFERENCES `masalama_carkila`.`Renter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feedback_Owner1`
    FOREIGN KEY (`Owner_id`)
    REFERENCES `masalama_carkila`.`Owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masalama_carkila`.`Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `masalama_carkila`.`Vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `make` VARCHAR(15) NOT NULL,
  `model` VARCHAR(15) NOT NULL,
  `year` YEAR NOT NULL,
  `color` VARCHAR(15) NOT NULL,
  `seatingCapacity` INT(2) NOT NULL,
  `engineNumber` VARCHAR(45) NOT NULL,
  `chassisNumber` VARCHAR(45) NOT NULL,
  `plateNumber` VARCHAR(10) NOT NULL,
  `Owner_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `plateNumber_UNIQUE` (`plateNumber` ASC),
  UNIQUE INDEX `engineNumber_UNIQUE` (`engineNumber` ASC),
  UNIQUE INDEX `chassisNumber_UNIQUE` (`chassisNumber` ASC),
  INDEX `fk_Vehicle_Owner1_idx` (`Owner_id` ASC),
  CONSTRAINT `fk_Vehicle_Owner1`
    FOREIGN KEY (`Owner_id`)
    REFERENCES `masalama_carkila`.`Owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masalama_carkila`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `masalama_carkila`.`Payment` (
  `id` INT NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `paymentAmount` DOUBLE NULL,
  `datePaid` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masalama_carkila`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `masalama_carkila`.`Booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `destination` VARCHAR(45) NOT NULL,
  `pickupLocation` VARCHAR(45) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `startTime` TIME NOT NULL,
  `endTime` TIME NOT NULL,
  `passengerNum` INT(2) NOT NULL,
  `rate` DOUBLE NOT NULL,
  `bookingStatus` VARCHAR(15) NOT NULL,
  `Vehicle_id` INT NOT NULL,
  `Payment_id` INT NOT NULL,
  `Renter_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Booking_Vehicle1_idx` (`Vehicle_id` ASC),
  INDEX `fk_Booking_Payment1_idx` (`Payment_id` ASC),
  INDEX `fk_Booking_Renter1_idx` (`Renter_id` ASC),
  CONSTRAINT `fk_Booking_Vehicle1`
    FOREIGN KEY (`Vehicle_id`)
    REFERENCES `masalama_carkila`.`Vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booking_Payment1`
    FOREIGN KEY (`Payment_id`)
    REFERENCES `masalama_carkila`.`Payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Booking_Renter1`
    FOREIGN KEY (`Renter_id`)
    REFERENCES `masalama_carkila`.`Renter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `masalama_carkila`.`Reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `masalama_carkila`.`Reports` (
  `id` INT NOT NULL,
  `reportName` VARCHAR(45) NOT NULL,
  `reportDescription` VARCHAR(45) NOT NULL,
  `Booking_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Reports_Booking1_idx` (`Booking_id` ASC),
  CONSTRAINT `fk_Reports_Booking1`
    FOREIGN KEY (`Booking_id`)
    REFERENCES `masalama_carkila`.`Booking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
